appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pJRFb+S+A0MuF8uSiPiR3q0BcvioYMIXBfOwFcTvsrnKlnXea8E2TzG8speBZ6tI18wLpbFELI8OU6sDpBAphekI7mkmxmtgr6dETA9LaEACkiq6CPr7CbmXpBf36CuThlxcPlQqCsY5wrdhIMYq84Xn74uelnGlTFmwYNCijjXqOmVkPQcUKimoth0ofZvajRX/8wrdiewXiYLrSuarixYQ6mfMuVvQT3/Djw9ocip+chCeFUKYD8aImVlD884N+SPcwZfDMn2b4+vXksr/p0X+tAnyWx6ne/0pv5Ap8m6WL6m3CGbTkR6fkFvXjJM8I2vctdhKSzk49Ih7g3HfHHfM/mZXovjO/vwyCYEqVq23YltXbP2ovrajdTjjmy/XzA7cOPzHyaw2ONrYdm8vQh/CmL//xr2HVz5USnr7sgra1MaEqVJGLKoU9U3hz1dbKcplILvFlk2BXwluB6S4MF03OLXkkWTQLkDWqK4TzJb9K7bbbRZfAn7iZegEMmmwEOSQ7vdYZrJlbHZsUkpWzFGP1PhYBvdSFFyVyilclQv+sg7u20b1sNduTVfjEVY1SqtHbtiVgTPAgzEOhd+RqOgNU+LyyV3rSxG60Gq9U+1f+Y7QxfMPSlAPgDDuy+Oqcu9yAETjLXRQL/uymKJry0mUI7cAmu0MPLmgbCkGyjs=}
conda_forge_output_validation: true
